server:
  port: 2230
spring:
  # 应用名称
  application:
    name: zuul
  banner:
    location: ["classpath:banner.txt", "file:./banner.txt"]
eureka:
  instance:
    instance-id: games    # 这个配置所有eureka client中必须一样！要么都不配，要么是同样的 instance-id ！否则，通过 routes 无法找到，也就不能访问
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2200/eureka/

zuul:
  routes:
    games-lobby:                  #路由名
      path: /games-lobby/**            #(针对微服务名称的)访问路径
      serviceId: lobby         #微服务名称
    upstair:
      path: /upstair/**      #(针对微服务名称的)访问路径
      serviceId: upstair         #微服务名称
      sensitiveHeaders: "*"   #解决session不一致的问题，如果接口中有session验证，加上这个，否则无需添加。
    lobby-api:
      path: /lobby-api/**      #(针对微服务名称的)访问路径
      serviceId: lobby-api         #微服务名称

